### ISSUE TITLE
tags please

### ISSUE THREAD

**Issue by alaniwi** [ES-DOC/esdoc-cdf2cim#10]
Hi, there are no tags, just some commit messages perhaps implying a version number. Could we have tags please (most recent and going forward, no need to back-populate beyond that).

Thanks.

**Comment by momipsl** [comment]
@alaniwi  The full release version history is [accessible via pypi](https://pypi.org/project/cdf2cim/#history).  However will ensure that each pypi release is also tagged in GitHub.

**Comment by alaniwi** [comment]
@momipsl Thanks.
